name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: oleksiyrudenko/gha-git-credentials@v1
      with:
        token: '${{ secrets.ACCESS_TOKEN }}'
    - run: |
        yarn
        yarn deploy

#     - name: Install packages
#       run: yarn

#     - name: Deploy
#       run: yarn deploy
